# fly.toml app configuration file generated for lovelace on 2024-12-02T10:47:41-05:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'lovelace'
primary_region = 'ewr'

[build]

[http_service]
internal_port = 3000
force_https = true
auto_stop_machines = 'off'
auto_start_machines = true
min_machines_running = 1
processes = ['app']

[[vm]]
memory = '16gb'
cpu_kind = 'shared'
cpus = 8

[mounts]
source = "data"
destination = "/data"
initial_size = "20gb"
